# Path to the kubeconfig file that connects to k8s apiserver.
kube-config: "~/.kube/config"
control-cluster-config: # 控制集群config文件
users-cluster-config:   # 用户集群config文件

# The address of a test cluster, it always like 192.168.129.30:6060.
baseurl: 127.0.0.1:6060
shceme: http
# The ID of test cluster.
cluster: kubernetes-stack

# preset resource
# If admin-tenant, admin-user and admin-password are not right, testcases will be fail in prepare phase.
# If tenant, password and password are not right, test framework will create right ones.
tenant: test
user: admin
password: Pwd123456
admin-tenant: system-tenant
admin-user: admin
admin-password: Pwd123456

# storage
# If set true, must input a existed storageclass or storage-info. Storage-info is used to
# create a stroage service in the plateform.
storage-enable: false
storageclass:
storage-info:

# cargo
# If set true, must input a available cargo-host service or cargo-info.
cargo-enable: false
cargo-host:

# cicd
# If set true, the namespace of CICD will be created. If there is no existing cyclone
# namespace, a specified namespace will be created.
cicd-enable: false

# elastic
# If set true, must input elastic info.
elastic-enable: false
elastic-address:

#Cargo Test Case Config
cargo.registry.username: admin
cargo.registry.password: Pwd123456
cargo.registry.basename: cntest
cargo.registry.cargoDomain: cntest.cargo.io
cargo.registry.imageRepo: cps-auth.cargo.io/release/nginx:1.15.5-alpine
cargo.registry.defaultRegistryName: default
cargo.registry.description: 自动化创建
cargo.registry.path: /Users/chenneng/Desktop/autotest/scm_code/zeus/devops/cntest.tar.gz

#Pipeline Test Case Config
pipeline.svn.server: http://172.19.30.61/svn/
pipeline.svn.url: SampleProject
pipeline.svn.run: 
pipeline.svn.user: cncn
pipeline.svn.password: qa2020
pipeline.svn.token: 

pipeline.bitbucket.server: http://172.19.30.59:7990/
pipeline.bitbucket.url: CNTES/cppdemo
pipeline.bitbucket.run: 
pipeline.bitbucket.user: admin
pipeline.bitbucket.password: qa2020
pipeline.bitbucket.token: MTgyODYxNTM2MjAzOjFtcU8bk4vY1sD797bVcdsKGqHL

pipeline.github.server: https://github.com
pipeline.github.url: chenne69163/cppdemo
pipeline.github.run: 
pipeline.github.user: 
pipeline.github.password: 
pipeline.github.token: c9612923112f2744671b2e1a7804e77c8e9e7e51

pipeline.gitlab.server: http://172.19.30.58:81
pipeline.gitlab.url: fufu/cntest20200103
pipeline.gitlab.run: 
pipeline.gitlab.user: fufu
pipeline.gitlab.password: admin123
pipeline.gitlab.token: c5o6YxuraCcrBtiAgGW4

pipeline.public.baseName: cntest
pipeline.public.nameSpace: 
pipeline.public.configSpace: 
pipeline.public.userTenant: system-tenant
pipeline.public.systemTenant: system-tenant
pipeline.public.pvcName: 
pipeline.public.pvcquota: 10Gi
pipeline.public.podName: 

